name: CI

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, World!
    - name: Run a multi-line script
      run: 
        echo add other actions to build,
        echo tset, and deploy your project.

#name: Build and Deploy
#on:
#  push:
#    branches:
#      - master

#jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Dependencies
#        run: npm install
#      - name: Build 
#        run: npm run build

  #deploy:
  #  name: Deploy
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Deploy to Firebase
  #      uses: w9jds/firebase-action@v1.1.0
  #      with:
  #        args: deploy
  #      env:
  #        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  #        PROJECT_ID: chez-mout
